# Generated by Django 4.0.5 on 2023-05-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('ConfigurationAdmin', 'ConfigurationAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('ExtraAdmin', 'ExtraAdmin'), ('ListDisplayAdmin', 'ListDisplayAdmin'), ('ListDisplayLinkAdmin', 'ListDisplayLinkAdmin'), ('ListFilterAdmin', 'ListFilterAdmin'), ('ShiftAdmin', 'ShiftAdmin'), ('ShiftExtraAdmin', 'ShiftExtraAdmin'), ('TeamAdmin', 'TeamAdmin'), ('WeekAdmin', 'WeekAdmin')], max_length=255, verbose_name='Модель')),
                ('field', models.CharField(max_length=255, verbose_name='Область')),
                ('order', models.PositiveIntegerField(verbose_name='Приказ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Фильтр списка',
                'verbose_name_plural': 'Список фильтров',
                'ordering': ['model', 'order', 'field'],
                'unique_together': {('model', 'order'), ('model', 'field')},
            },
        ),
        migrations.CreateModel(
            name='ListDisplayLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('ConfigurationAdmin', 'ConfigurationAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('ExtraAdmin', 'ExtraAdmin'), ('ListDisplayAdmin', 'ListDisplayAdmin'), ('ListDisplayLinkAdmin', 'ListDisplayLinkAdmin'), ('ListFilterAdmin', 'ListFilterAdmin'), ('ShiftAdmin', 'ShiftAdmin'), ('ShiftExtraAdmin', 'ShiftExtraAdmin'), ('TeamAdmin', 'TeamAdmin'), ('WeekAdmin', 'WeekAdmin')], max_length=255, verbose_name='Модель')),
                ('field', models.CharField(max_length=255, verbose_name='Область')),
                ('order', models.PositiveIntegerField(verbose_name='Приказ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Список отображаемых ссылок',
                'verbose_name_plural': 'Список отображаемых ссылок',
                'ordering': ['model', 'order', 'field'],
                'unique_together': {('model', 'order'), ('model', 'field')},
            },
        ),
        migrations.CreateModel(
            name='ListDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('ConfigurationAdmin', 'ConfigurationAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('ExtraAdmin', 'ExtraAdmin'), ('ListDisplayAdmin', 'ListDisplayAdmin'), ('ListDisplayLinkAdmin', 'ListDisplayLinkAdmin'), ('ListFilterAdmin', 'ListFilterAdmin'), ('ShiftAdmin', 'ShiftAdmin'), ('ShiftExtraAdmin', 'ShiftExtraAdmin'), ('TeamAdmin', 'TeamAdmin'), ('WeekAdmin', 'WeekAdmin')], max_length=255, verbose_name='Модель')),
                ('field', models.CharField(max_length=255, verbose_name='Область')),
                ('order', models.PositiveIntegerField(verbose_name='Приказ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Отображение списка',
                'verbose_name_plural': 'Отображение списка',
                'ordering': ['model', 'order', 'field'],
                'unique_together': {('model', 'order'), ('model', 'field')},
            },
        ),
    ]
